### ISSUE TITLE
[bug]:can not upload big file over 20 GB

### ISSUE THREAD

**Issue by zbaiyy01** [aohanhongzhi/air-share#2]

**Comment by aohanhongzhi** [comment]
After testing, it was indeed true, because the type used in the code was incorrect, resulting in an overflow of integers.

After testing, it was indeed true, because the type used in the code was incorrect, resulting in an overflow of integers.
To solve this problem, I changed the integer to long . you can test it again.

![image](https://github.com/aohanhongzhi/air-share/assets/37319319/2b6de028-7978-4e93-92f8-940b7f09d992)

**Comment by aohanhongzhi** [comment]
https://github.com/aohanhongzhi/air-share/commit/10c83e0c1c0e064418389dd32e921e4e8a0df970
